# Generated by Django 5.0.7 on 2024-10-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='is_dir',
            field=models.BooleanField(default=False),
        ),
    ]
