# Generated by Django 5.0.7 on 2024-10-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_filemetadata_is_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemetadata',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
