# Generated by Django 5.0.7 on 2024-10-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_remove_filemetadata_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='is_public',
        ),
        migrations.AddField(
            model_name='directory',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
