# Generated by Django 5.0.7 on 2024-10-17 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='last_position',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
