# Generated by Django 5.0.7 on 2024-10-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_movie_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='allow_sub_dir',
            field=models.BooleanField(default=False),
        ),
    ]
