# Generated by Django 5.0.7 on 2024-11-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_rename_filemetadata_filesearchmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('extensions', models.TextField(help_text='Comma-separated list of file extensions, e.g., .jpg,.png,.gif')),
            ],
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relative_path', models.CharField(max_length=1024, unique=True)),
                ('absolute_path', models.CharField(max_length=2048, unique=True)),
                ('is_dir', models.BooleanField(default=False)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('modified', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('file_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.filetypecategory')),
            ],
        ),
    ]
